:sparkles: don't display dropdown menu if 2FA not setup
maykinmedia/django-admin-index pull request #54
Opened 2021-08-11 15:10 UTC by azertyValentin

2021-08-11 15:29 UTC, annashamray requested changes
I don't think this is a right place for this change

If dropdown should not be displayed in the login page, the login page template in the 2FA lib should be modified. 

`admin_index` should not rely on 2FA environment variables

2021-08-11 18:03 UTC, azertyValentin commented
> I don't think this is a right place for this change
> 
> If dropdown should not be displayed in the login page, the login page template in the 2FA lib (or in your specific project) should be modified.
> 
> `admin_index` should not rely on 2FA environment variables

I agree, my last commit fix this issue

2021-08-12 10:33 UTC, sergei-maertens requested changes

2021-08-12 10:33 UTC, sergei-maertens commented on django_admin_index/templatetags/django_admin_index.py
> +    return settings.DISPLAY_DROP_DOWN_MENU_CONDITION_FUNCTION(request)
The setting should be a string value, something like `"django_admin_index.utils.should_display_dropdown_menu"`.

You can then import this function using `django.utils.module_loading.import_string` and invoke it:

```suggestion
def display_dropdown_menu(request):
    func = import_string(settings.DISPLAY_DROP_DOWN_MENU_CONDITION_FUNCTION)
    return func(request)
```

This makes it possible to pass the function to use as an environment variable.

2021-08-12 10:33 UTC, sergei-maertens commented on django_admin_index/conf.py
> +
Please move this to `django_admin_index.utils.should_display_dropdown_menu`, and change the implementation to contain the code that is now in the template:

```py
def should_display_dropdown_menu(request):
    return admin_index_settings.SHOW_MENU and request.user.is_authenticated and request.user.is_staff
```

2021-08-12 10:33 UTC, sergei-maertens commented on django_admin_index/templates/admin/base.html
> +        {% if display_dropdown == True %}
Using the above changes in the functions, please simplify the template:

```django
{% display_dropdown_menu request as should_display_dropdown %}
{% if should_display_dropdown and dashboard_app_list %}
...
```

2021-08-12 15:55 UTC, sergei-maertens approved these changes

2021-08-12 15:55 UTC, merged